schema_version = "1.0.0"

id = "icelayers"
version = "0.1.0"
name = "IceLayers"
tagline = "Fast Ucupaint layer navigation"
maintainer = "Rheez"
type = "add-on"

website = "https://github.com/Rheez-1337/IceLayers"

tags = ["Paint", "Node", "Material"]

blender_version_min = "5.0.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2025 Rheez"
]
